import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Partners from "../components/Partners";
import Benefits from "../components/Benefits";
import Esteem from "../components/Esteem";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <div className="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <Header />
        <Hero />
        <Partners />
        <Benefits />
        <Esteem />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
